apiVersion: v1
kind: ServiceAccount
metadata:
  name: orphaned-pvc-scanner
  namespace: orphaned-pvc-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orphaned-pvc-scanner
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orphaned-pvc-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orphaned-pvc-scanner
subjects:
  - kind: ServiceAccount
    name: orphaned-pvc-scanner
    namespace: orphaned-pvc-scanner
