apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-cleaner
  namespace: pvc-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-cleaner
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvc-cleaner
subjects:
  - kind: ServiceAccount
    name: pvc-cleaner
    namespace: pvc-cleaner
