apiVersion: v1
kind: ServiceAccount
metadata:
  name: template-pvc-scanner
  namespace: template-pvc-scanner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-pvc-scanner
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: template-pvc-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: template-pvc-scanner
subjects:
  - kind: ServiceAccount
    name: template-pvc-scanner
    namespace: template-pvc-scanner
